"""empty message

Revision ID: ae1e1c2d3b3c
Revises: 
Create Date: 2020-11-19 10:01:36.295419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1e1c2d3b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('comment_path', sa.String(length=256), nullable=True),
    sa.Column('review_path', sa.String(length=256), nullable=True),
    sa.Column('log_path', sa.String(length=256), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('alarm',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=True),
    sa.Column('kakao', sa.Boolean(), nullable=True),
    sa.Column('line', sa.Boolean(), nullable=True),
    sa.Column('f_message', sa.Boolean(), nullable=True),
    sa.Column('instar_dm', sa.Boolean(), nullable=True),
    sa.Column('twitter_dm', sa.Boolean(), nullable=True),
    sa.Column('sms', sa.Boolean(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['task.user_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('contents',
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['task.user_id'], ),
    sa.PrimaryKeyConstraint('contents_id', 'task_id', 'user_id')
    )
    op.create_index(op.f('ix_contents_name'), 'contents', ['name'], unique=False)
    op.create_table('task_sharing',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['task.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'admin_id', 'user_id')
    )
    op.create_table('alarm_time',
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['alarm.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['alarm.user_id'], ),
    sa.PrimaryKeyConstraint('alarm_id', 'task_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm_time')
    op.drop_table('task_sharing')
    op.drop_index(op.f('ix_contents_name'), table_name='contents')
    op.drop_table('contents')
    op.drop_table('alarm')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
